stages: 
    - stage: CheckTitleStage
      jobs:
      - job: CleanSteps
        timeoutInMinutes: 5
        workspace:
            clean: all
      - job: GetPRTitle
        timeoutInMinutes: 5
        steps:
        - task: PowerShell@2
          name: SetTitle
          displayName: "Getting PR title from azure"
          inputs:
            targetType: "inline"
            script: |
                # Call the Azure DevOps Services Rest API.
                $url = "$($env:SYSTEM_TEAMFOUNDATIONCOLLECTIONURI)$env:SYSTEM_TEAMPROJECTID/_apis/git/repositories/$(Build.Repository.ID)/pullRequests/$(System.PullRequest.PullRequestId)?api-version=7.0"
                $headers = @{
                    Authorization = "Bearer $(System.AccessToken)"
                }
                $pullRequestInfo = Invoke-RestMethod -Uri $url -Method 'GET' -ContentType 'application/json' -Headers $headers
                $json = $($pullRequestInfo | ConvertTo-Json -Depth 100 | ConvertFrom-Json)
                $description = $json.description
                $title = $json.title
                echo "$title"
                echo "##vso[task.setvariable variable=prTitle]$title"
                echo "##vso[task.setvariable variable=testingTitle;isoutput=true]$title"
        - task: PowerShell@2
          displayName: "Validate the PR title format"
          inputs:
           targetType: "filePath"
           filePath: "pipeline/validate_conventional_commit.ps1"
           arguments: "'$(prTitle)'"
           failOnStderr: true
