parameters:
- name: StageDependencies
  type: object
  default: []

stages: 
  - stage: FlutterCleanBeforeAppBuild
    dependsOn: ${{ parameters.StageDependencies }}
    condition: succeeded()
    jobs:
    - job: Build
      timeoutInMinutes: 30
      steps:
        - task: FlutterCommand@0
          displayName: "Flutter Clean"
          inputs:
            projectDirectory: '.'
            flutterDirectory: '/Users/user/fvm/versions/$(flutterVersion)/bin'
            arguments: 'clean'
        - task: FlutterBuild@0
          displayName: Build Android
          inputs:
            target: "apk"
            projectDirectory: "."
            flutterDirectory: "/Users/user/fvm/versions/$(flutterVersion)/bin"
            buildFlavour: "$(flavor)"
            entryPoint: "lib/main.dart"
            extraArgs: '--debug --dart-define-from-file env/$(flavor)-env.json'
        - task: FlutterBuild@0
          displayName: Build iOS
          inputs:
            target: 'ios'
            projectDirectory: '.'
            flutterDirectory: '/Users/user/fvm/versions/$(flutterVersion)/bin'
            buildFlavour: '$(flavor)'
            entryPoint: 'lib/main.dart'
            iosCodesign: false
            extraArgs: '--dart-define-from-file env/$(flavor)-env.json'