name: dumbdumb_flutter_app
description: My dumbdumb Flutter app
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.27.0"

dependencies:
  provider: ^6.1.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

  # System/Structure
  go_router: ^14.6.3
  recaptcha_enterprise_flutter: ^18.6.1

  # Device Info
  device_info_plus: ^11.2.1
  package_info_plus: ^8.1.3
  store_redirect: ^2.0.3
  permission_handler: ^11.3.1
  jailbreak_root_detection: ^1.1.5

  # Image
  image_picker: ^1.1.2
  image_picker_android: ^0.8.12+20
  image_picker_platform_interface: ^2.10.1
  flutter_image_compress: ^2.4.0

  # Data
  dio: ^5.7.0
  shared_preferences: ^2.3.5
  file: ^7.0.1

  # Firebase
  firebase_core: ^3.10.1
  firebase_analytics: ^11.4.1
  firebase_messaging: ^15.2.1
  firebase_crashlytics: ^4.3.1
  firebase_remote_config: ^5.3.1

  # Push Notification
  flutter_local_notifications: ^18.0.1
  cached_network_image: ^3.4.1
  photo_view: ^0.15.0
  flutter_easyloading: ^3.0.5
  fluttertoast: ^8.2.10
  version: ^3.0.2
  collection: ^1.19.0
  url_launcher: ^6.3.1
  file_picker: ^8.1.7
  path: ^1.9.0
  adaptive_widgets_flutter: ^0.1.3
  internet_connection_checker_plus: ^2.7.0
  infinite_scroll_pagination: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  cobertura: ^1.0.5

flutter:
  uses-material-design: true
  generate: true
flutter_intl:
  enabled: true
